# Gather news data

In [40]:
from newscatcherapi import NewsCatcherApiClient
import pandas as pd
import json
import time

In [104]:
#API_KEY = '7wJbVyTAlWVhCC_UsmK3gcKuAuZtnModpdCa1L_rKr4' #testing
#API_KEY = 'SR0nnHSvKHxy0r6rVAL0PeG7dWR7jDMhhUAcrsXeWwc' #512275sw@eur.nl - USED 0 left
#API_KEY = 'ECLG-o9l4x4QtiqGCnGclXW-ufsCKb6QEGZc0do59PY' #512275sw@student.eur.nl - USED 0 left
#API_KEY = 'AOl30mi3uzQ2-Y_AQo5n2zxMpI3LpUzvYttPFzEY8u8' #willemse@rsm.nl - USED 0 left
#API_KEY = 'k2bBpn21tawm8DlrHeaK_S0BAZlSRIBIOGmIhrxoebg' #89874swi@eur.nl - USED - 0 left
#API_KEY = 'EmeAWih7e94TA_Se2L2UWKpf2aO5SOiyomFWe3kMy2A' #1057811@hr.nl - USED - 0 left

newscatcherapi = NewsCatcherApiClient(x_api_key=API_KEY)

In [105]:
df_news = pd.DataFrame(columns=["date", 'url', "author", "title", "topic",  "summary", "q"])

In [106]:
def call_API_dataframe(q, date_from, page):
    temp_articles = newscatcherapi.get_search(q=q, from_=date_from, lang='en', page_size=100, page=page)
    for i in range(len(temp_articles['articles'])):
        temp_row = [temp_articles['articles'][i]["published_date"], temp_articles['articles'][i]["clean_url"], temp_articles['articles'][i]["author"],
                temp_articles['articles'][i]["title"], temp_articles['articles'][i]["topic"], temp_articles['articles'][i]["summary"], q]
        df_news.loc[len(df_news)] = temp_row
    path = r'C:\Users\Sten\Documents\EUR BAM\Thesis\data\newscatcher' + '\\' + q + str(page) + '.json'
    with open(path, "w") as file:
        json.dump(temp_articles, file)
    time.sleep(1)

In [108]:
for i in range(1, 50):
    call_API_dataframe(q='finance OR financial', date_from='1 month ago', page=i)
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49

In [64]:
for i in range(1, 3):
    call_API_dataframe(q='election OR elections', date_from='2 weeks ago', page=i)
    print(i)

1
2

In [109]:
df_news

,date,url,author,title,topic,summary,q
0,2023-04-18 18:30:00,blogtalkradio.com,Vernas Help Metroplex Buzz,The Role of a Finance Controller in Upton,news,The finance controller's responsibilities incl...,finance OR financial
1,2023-04-17 03:30:00,scoop.co.nz,Find More,The Basics Of Business Finance: A Comprehensiv...,news,"Monday, 17 April 2023, 2:01 pm\n \nPress Relea...",finance OR financial
2,2023-04-25 11:53:28,techbullion.com,Ali Bajwa,Finance Courses: The Gateway to Your Financial...,news,Are you struggling with managing your personal...,finance OR financial
3,2023-04-22 07:35:49,ghanaweb.com,,Financial literacy key to SMEs' access to funding,news,The Executive Director at the Centre for Finan...,finance OR financial
4,2023-04-22 00:00:00,mdpi.com,Yuting Tu,Game Theory Analysis of Chinese DC/EP Loan and...,science,"School of Economics and Management, University...",finance OR financial
...,...,...,...,...,...,...,...
4895,2023-04-21 17:00:29,bitcoinist.com,Review Site,The rise of Shiba Inu confirms that tokens lik...,news,The cryptocurrency market is full of surprises...,finance OR financial
4896,2023-04-18 20:15:00,reliefweb.int,,Chief Operations/Finance Manager,economics,The Role\n\nWe are seeking to recruit an exper...,finance OR financial
4897,2023-04-20 00:00:00,globenewswire.com,Tecnoglass Inc.,Tecnoglass Announces Long Term Strategic Partn...,news,"Barranquilla, Colombia, April 20, 2023 (GLOBE ...",finance OR financial
4898,2023-04-19 13:00:00,nbc15.com,,National Subcontractor Market Report Reveals $...,news,"Despite this resulting in crunched margins, th...",finance OR financial
4899,2023-05-09 22:02:22,thescottishsun.co.uk,Ryan Rowe,Rangers in recruitment drive for key new role ...,news,RANGERS are on the search for a new finance ch...,finance OR financial

In [110]:
df_news.to_csv(r'C:\Users\Sten\Documents\EUR BAM\Thesis\data\news\finance.csv', index=False)